CREATE TABLE IF NOT EXISTS exercises (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

INSERT INTO exercises (id, name) VALUES
  ('1', 'Supino reto'),
  ('2', 'Supino inclinado'),
  ('3', 'Supino declinado'),
  ('4', 'Crucifixo'),
  ('5', 'Crossover'),
  ('6', 'Puxada frente'),
  ('7', 'Puxada aberta'),
  ('8', 'Remada curvada'),
  ('9', 'Remada baixa'),
  ('10', 'Remada unilateral'),
  ('11', 'Barra fixa'),
  ('12', 'Desenvolvimento'),
  ('13', 'Elevacao lateral'),
  ('14', 'Elevacao frontal'),
  ('15', 'Crucifixo inverso'),
  ('16', 'Encolhimento'),
  ('17', 'Rosca direta'),
  ('18', 'Rosca alternada'),
  ('19', 'Rosca martelo'),
  ('20', 'Rosca scott'),
  ('21', 'Rosca concentrada'),
  ('22', 'Triceps polia'),
  ('23', 'Triceps testa'),
  ('24', 'Triceps mergulho'),
  ('25', 'Triceps coice'),
  ('26', 'Agachamento livre'),
  ('27', 'Leg press'),
  ('28', 'Cadeira extensora'),
  ('29', 'Cadeira flexora'),
  ('30', 'Mesa flexora'),
  ('31', 'Stiff'),
  ('32', 'Levantamento terra'),
  ('33', 'Afundo'),
  ('34', 'Passada'),
  ('35', 'Panturrilha em pe'),
  ('36', 'Panturrilha sentado'),
  ('37', 'Abdominal tradicional'),
  ('38', 'Abdominal infra'),
  ('39', 'Abdominal obliquo'),
  ('40', 'Prancha'),
  ('41', 'Elevacao de pernas'),
  ('42', 'Esteira'),
  ('43', 'Bicicleta'),
  ('44', 'Eliptico'),
  ('45', 'Escada'),
  ('46', 'Corda')
ON CONFLICT (id) DO NOTHING;
