CREATE TABLE IF NOT EXISTS exercises (
  code TEXT PRIMARY KEY,
  category TEXT NOT NULL
);

INSERT INTO exercises (code, category) VALUES
  ('SUPINO_RETO', 'Peito'),
  ('SUPINO_INCLINADO', 'Peito'),
  ('SUPINO_DECLINADO', 'Peito'),
  ('CRUCIFIXO', 'Peito'),
  ('CROSSOVER', 'Peito'),
  ('PUXADA_FRENTE', 'Costas'),
  ('PUXADA_ABERTA', 'Costas'),
  ('REMADA_CURVADA', 'Costas'),
  ('REMADA_BAIXA', 'Costas'),
  ('REMADA_UNILATERAL', 'Costas'),
  ('BARRA_FIXA', 'Costas'),
  ('DESENVOLVIMENTO', 'Ombros'),
  ('ELEVACAO_LATERAL', 'Ombros'),
  ('ELEVACAO_FRONTAL', 'Ombros'),
  ('CRUCIFIXO_INVERSO', 'Ombros'),
  ('ENCOLHIMENTO', 'Ombros'),
  ('ROSCA_DIRETA', 'Biceps'),
  ('ROSCA_ALTERNADA', 'Biceps'),
  ('ROSCA_MARTELO', 'Biceps'),
  ('ROSCA_SCOTT', 'Biceps'),
  ('ROSCA_CONCENTRADA', 'Biceps'),
  ('TRICEPS_POLIA', 'Triceps'),
  ('TRICEPS_TESTA', 'Triceps'),
  ('TRICEPS_MERGULHO', 'Triceps'),
  ('TRICEPS_COICE', 'Triceps'),
  ('AGACHAMENTO_LIVRE', 'Pernas'),
  ('LEG_PRESS', 'Pernas'),
  ('CADEIRA_EXTENSORA', 'Pernas'),
  ('CADEIRA_FLEXORA', 'Pernas'),
  ('MESA_FLEXORA', 'Pernas'),
  ('STIFF', 'Pernas'),
  ('LEVANTAMENTO_TERRA', 'Pernas'),
  ('AFUNDO', 'Pernas'),
  ('PASSADA', 'Pernas'),
  ('PANTURRILHA_EM_PE', 'Pernas'),
  ('PANTURRILHA_SENTADO', 'Pernas'),
  ('ABDOMINAL_TRADICIONAL', 'Abdomen'),
  ('ABDOMINAL_INFRA', 'Abdomen'),
  ('ABDOMINAL_OBLIQUO', 'Abdomen'),
  ('PRANCHA', 'Abdomen'),
  ('ELEVACAO_PERNAS', 'Abdomen'),
  ('ESTEIRA', 'Cardio'),
  ('BICICLETA', 'Cardio'),
  ('ELIPTICO', 'Cardio'),
  ('ESCADA', 'Cardio'),
  ('CORDA', 'Cardio')
ON CONFLICT (code) DO NOTHING;
