ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS name TEXT;

UPDATE users
SET name = ''
WHERE name IS NULL;

ALTER TABLE IF EXISTS users
  ALTER COLUMN name SET NOT NULL;

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  birthdate DATE NULL,
  weight_kg NUMERIC NULL,
  height_cm NUMERIC NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
