CREATE TABLE IF NOT EXISTS workout_dones (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  workout_id TEXT NOT NULL REFERENCES workouts(id) ON DELETE CASCADE,
  done_at TIMESTAMP NOT NULL DEFAULT NOW()
);
